# Generated by Django 3.0.2 on 2020-01-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='plate_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
